// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// converter_ra_
SEXP converter_ra_(Rcpp::RObject x);
RcppExport SEXP _validaRA_converter_ra_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(converter_ra_(x));
    return rcpp_result_gen;
END_RCPP
}
// valida_ra
SEXP valida_ra(SEXP x, SEXP type, SEXP log);
RcppExport SEXP _validaRA_valida_ra(SEXP xSEXP, SEXP typeSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type type(typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(valida_ra(x, type, log));
    return rcpp_result_gen;
END_RCPP
}
// generate_digit
void generate_digit(Rcpp::RObject x, SEXP type);
RcppExport SEXP _validaRA_generate_digit(SEXP xSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type type(typeSEXP);
    generate_digit(x, type);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_validaRA_converter_ra_", (DL_FUNC) &_validaRA_converter_ra_, 1},
    {"_validaRA_valida_ra", (DL_FUNC) &_validaRA_valida_ra, 3},
    {"_validaRA_generate_digit", (DL_FUNC) &_validaRA_generate_digit, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_validaRA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
