// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// converter_ra_
SEXP converter_ra_(Rcpp::RObject x);
RcppExport SEXP validaRA_converter_ra_(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(converter_ra_(x));
    return rcpp_result_gen;
END_RCPP
}
// valida_ra
SEXP valida_ra(SEXP x, SEXP type, SEXP log);
RcppExport SEXP validaRA_valida_ra(SEXP xSEXP, SEXP typeSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type type(typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(valida_ra(x, type, log));
    return rcpp_result_gen;
END_RCPP
}
// generate_digit_pis
void generate_digit_pis(Rcpp::RObject x);
RcppExport SEXP validaRA_generate_digit_pis(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type x(xSEXP);
    generate_digit_pis(x);
    return R_NilValue;
END_RCPP
}
