// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// valida_cpf
LogicalVector valida_cpf(Rcpp::CharacterVector x);
RcppExport SEXP validaRA_valida_cpf(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(valida_cpf(x));
    return rcpp_result_gen;
END_RCPP
}
// valida_cpf_log
Rcpp::DataFrame valida_cpf_log(Rcpp::CharacterVector x);
RcppExport SEXP validaRA_valida_cpf_log(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(valida_cpf_log(x));
    return rcpp_result_gen;
END_RCPP
}
// valida_cnpj
LogicalVector valida_cnpj(Rcpp::CharacterVector x);
RcppExport SEXP validaRA_valida_cnpj(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(valida_cnpj(x));
    return rcpp_result_gen;
END_RCPP
}
// valida_pis
LogicalVector valida_pis(Rcpp::CharacterVector x);
RcppExport SEXP validaRA_valida_pis(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(valida_pis(x));
    return rcpp_result_gen;
END_RCPP
}
