# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

converter_ra_ <- function(x) {
    .Call('validaRA_converter_ra_', PACKAGE = 'validaRA', x)
}

valida_ra <- function(x, type, log) {
    .Call('validaRA_valida_ra', PACKAGE = 'validaRA', x, type, log)
}

generate_digit <- function(x, type) {
    invisible(.Call('validaRA_generate_digit', PACKAGE = 'validaRA', x, type))
}

